# Generated by Django 5.2.7 on 2025-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('total_workdays', models.IntegerField()),
                ('total_beneficiaries', models.IntegerField()),
                ('total_funds_disbursed', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('state', 'district', 'month', 'year')},
            },
        ),
    ]
