# Generated by Django 5.2.7 on 2025-10-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='districtdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='approved_labour_budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='avg_days_employment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='avg_wage_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='differently_abled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='fin_year',
            field=models.CharField(default='2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='total_individuals_worked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='wages',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='women_persondays',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='districtdata',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='districtdata',
            name='total_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='districtdata',
            name='total_funds_disbursed',
        ),
        migrations.RemoveField(
            model_name='districtdata',
            name='total_workdays',
        ),
        migrations.RemoveField(
            model_name='districtdata',
            name='year',
        ),
    ]
